### ISSUE TITLE
Ran into issue compiling with openjdk 

### ISSUE THREAD

**Issue by Cinemacloud** [stefanhaustein/TerminalImageViewer#11]
Would say 100 times TerminalImageViewer.java:305: error: unmappable character for encoding ASCII
        0x06600660, '\u254f',  //??Heavy double dash vertical

Found adding " -encoding ISO-8859-1" to javac fixed it.

**Comment by stefanhaustein** [comment]
Probably a nbsp in the comment. Should be fixed at head now. Let me know if there are more similar issues. Thanks for the report!

**Comment by stefanhaustein** [comment]
p.s. Now replaced all the other occurrences not just the one in line 305
