### ISSUE TITLE
[Urgent] (easier than easy) Make new release to push the patch for the initialization error

### ISSUE THREAD

**Issue by aaronliu0130** [stefanhaustein/TerminalImageViewer#113]
**Is your feature request related to a problem? Please describe.(Optional)**
Downloading the latest release, you get the initialization error as shown in #87 

**Describe the solution you'd like**
Make release v1.1.1

**Describe alternatives you've considered**
Ping the owner a million times to let them accept this request

**Additional context**
This is verily needed for homebrew support

**Comment by stefanhaustein** [comment]
Thanks, done!
