### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by doekman** [stefanhaustein/TerminalImageViewer#114]
With installing on Mac, brew couldn't find the formula.

With `brew install tiv`, brew performed a `brew update --preinstall`, but that didn't fix it.

After running `brew update`, tiv did install.

You might want to add a comment to option 1 that `brew update` might be necessary. This error will fade with time though...

**Comment by aaronliu0130** [comment]
If `brew update --preinstall` didn't fix it then one thing probably went wrong in the process. `brew update --preinstall` should update formulae.
`brew update` is mentioned in Homebrew's official README in the troubleshooting section, so I doubt that this is needed.
