### ISSUE TITLE
[Question] Recent KDE Konsole code and terminal image viewer - progress and change?

### ISSUE THREAD

**Issue by rubyFeedback** [stefanhaustein/TerminalImageViewer#116]
Hey there,

KDE konsole has changed a lot over the years. I'd love to view images in KDE konsole,
perhaps even animated .gif files. \o/

I have a more serious use case, though. I have a commandline application that asks
an exam question; then I want to show an image. I can do this via the web in rails,
but I also want a commandline variant. But I don't know how feasible that is.

Would Terminal image viewer fit that bill? Or has kde konsole itself gained
that ability already? I read something on kde reddit but who knows what is true
there. Any docu on the main README here would be super useful.

**Comment by aaronliu0130** [comment]
For such an application, you would need something precise, so why would you want to display it in a terminal emulator? Just execute the path and it'll open in the default program.
