### ISSUE TITLE
More examples to the README; and is it possible to get a higher quality of the image?

### ISSUE THREAD

**Issue by rubyFeedback** [stefanhaustein/TerminalImageViewer#117]
I just tested "tiv", quite useful. But the image displayed is a bit blurry. Is there a way to make it sharper?

Also some more examples may be useful to tweak tiv. I only found fonts support (I think?) via the github issue tracker (haven't tried it yet but will soon try it).

**Comment by aaronliu0130** [comment]
1. Inquiry: What do you mean by "blurry"?
2. I'm sure the examples are enough, is there any reason to possibly include more?

**Comment by aaronliu0130** [comment]
If you wish to reopen, please respond
