### ISSUE TITLE
Replace "Question" template with GitHub Discussions

### ISSUE THREAD

**Issue by aaronliu0130** [stefanhaustein/TerminalImageViewer#120]
### Is your feature request related to a problem? Please describe.

I hate it when questions get into the issues section, as this section is mainly for reports instead of questions.

### Describe the solution you'd like

From the repository settings page, enable discussions and remove/replace the question template with a notice telling to use discussions instead. I can do the latter part but I can't change the settings. GitHub Discussions feels more like a forum and is more suited for this purpose.

### Describe alternatives you've considered

Just don't change anything, but the problem still exists and the armies of the questions issue templates would constantly attack my conscience. 

### Additional context

This can also be used as a reference for what issue forms look like.

**Comment by aaronliu0130** [comment]
@stefanhaustein changing the settings should be easy.

**Comment by stefanhaustein** [comment]
Done
