### ISSUE TITLE
sh: 1: convert: not found

### ISSUE THREAD

**Issue by Dmole** [stefanhaustein/TerminalImageViewer#13]
```
# ./tiv e.jpg 
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'e.jpg'.
File format not recogmized for 'e.jpg'

# file tiv
tiv: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=7d7a066788b8a442acee9a988c25e0f67833ff95, stripped

# grep convert tiv.cpp

# uname -r
4.9.41-00428-g6553404
```

**Comment by stefanhaustein** [comment]
Which OS? Cimg automatically uses some installed format libraries, perhaps try 

    apt-get install libjpeg

**Comment by Dmole** [comment]
# cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

apt install libjpeg9

Did not help. (There is no package without a version)

**Comment by Dmole** [comment]
`apt install imagemagick`

fixed this error but the output is garbled...

**Comment by stefanhaustein** [comment]
Thanks for the patch! On MacOS, you might want to try -256. But I think there will still be gaps between the rows, so it doesn't really look pretty. Your milage might vary depending on the terminal....

**Comment by Dmole** [comment]
`-256` fixed the garbled output, that should really be documented with a -h parameter.
