### ISSUE TITLE
Please share your GPG key you use to sign release tags

### ISSUE THREAD

**Issue by vt-alt** [stefanhaustein/TerminalImageViewer#133]
You have `v1.2.1` tag signed (which is good) can you share your GPG you used for signing so the tag could be verified?

### Describe alternatives you've considered

Cannot find it on standard servers nor on https://github.com/stefanhaustein.gpg

**Comment by aaronliu0130** [comment]
1. Note the releaser. The release author is me, so you should be looking for my GPG key, which is where you expect.
2. For some older commits that are verified, that is because GitHub signs everything created on GitHub (and not committed locally) with their GPG key.

**Comment by vt-alt** [comment]
Thanks!
