### ISSUE TITLE
unrecognized file format

### ISSUE THREAD

**Issue by sysadminpower2019** [stefanhaustein/TerminalImageViewer#134]
### Describe the Bug

tiv will not working when trying to view a jpg downloaded from the internet

error is 

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<uint8>::load(): Failed to recognize format of file '300.jpg'.
Error: '300.jpg' has an unrecognized file format

### To Reproduce

download image 
run tiv 300.jpg

### Expected Behavio(u)r

image should work

### Version/Commit Hash

latest 

### OS Specifics

Linux house 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by stefanhaustein** [comment]
Closing as we can't repro without the image in question. If the problem persists, please provide an image to debug.
