### ISSUE TITLE
At execution of make, which was successful, there was an output re: an unused variable FLAG_24BIT in tiv.cpp

### ISSUE THREAD

**Issue by b9Joker108** [stefanhaustein/TerminalImageViewer#135]
### Describe the Bug

At execution of `make`, which was successful, there was an output re: an unused variable FLAG_24BIT in tiv.cpp

### To Reproduce

1. Execute `make`
2. Successful, but outputs about the above unused variable 

### Expected Behavio(u)r

I didn't expect to see this output. I just wanted to let you know so that it may be repaired. 

### Screenshots

![2024-01-04-15-42-59-787](https://github.com/stefanhaustein/TerminalImageViewer/assets/147242971/c62bc7f6-0460-477c-9a67-5068357f7cf5)

### Version/Commit Hash

Cloned from source

### OS Specifics

Linux localhost 5.15.78-android13-8-26966632-abX910XXU1AWHA #1 SMP PREEMPT Fri Aug 11 13:12:49 UTC 2023 aarch64 Android

**Comment by aaronliu0130** [comment]
It’s just a warning, you can ignore it.
