### ISSUE TITLE
Noisy color output with indexed-color, few-color source images.

### ISSUE THREAD

**Issue by klopsi** [stefanhaustein/TerminalImageViewer#15]
LOVE it! However I can't get indexed-color images to come out with a clean mapping of colors.

The best I could do with the Google logo was this: http://imgur.com/8yZJpgOl.png

I would love it if the program could limit output colors to the colors used in an indexed-color image, or if you could limit it to the 16 colors used in IRC. https://en.wikichip.org/wiki/irc/colors
Also awesome would be if it could output IRC colors directly (control code 0x03+FG_COLOR,BG_COLOR) before each color change, but I can do that with a script.

I'd gladly donate to help. Can't program well enough to do it myself :( CHEERS

**Comment by stefanhaustein** [comment]
The gray borders stem from re-distribution of the color values of unmatched pixels, so the sum of the rgb values matches. Should be straightforward to add some kind of special handling for the case where a lot of pixels have exactly the same value. You might be able to get better results with the -256 option already.

**Comment by klopsi** [comment]
Thank you for the answer!  I made my own converter which picks nearest two colors that match the most common colors in the 4x4 block - it doesn't do error-propagation.  This seems to work best for these 16 color images.  Thanks for the inspiration.

**Comment by stefanhaustein** [comment]
Reopening: still want to address this anyway

**Comment by stefanhaustein** [comment]
Update: Should be fixed at head now with a69ffa848d2bdd77032262ff6375839b24d8727b.
Can you give it a try with the same image to see if it's actually better in your case? O:)

**Comment by klopsi** [comment]
Much improved!
https://i.imgur.com/bS59028l.png

Works much better with black background btw. 
https://i.imgur.com/h4R0S2Il.png

;) Cheers!

**Comment by stefanhaustein** [comment]
The difference might stem from different degrees of anti-aliasing: The indexed color cases is triggered if the  two most frequent colors cover more than 25% (IIRC) of the cell
