### ISSUE TITLE
cpp version isn't uses skew blocks

### ISSUE THREAD

**Issue by denizzzka** [stefanhaustein/TerminalImageViewer#16]

**Comment by denizzzka** [comment]
Or I am just use wrong font. Need to recheck.

**Comment by denizzzka** [comment]
Huh, these block is commented out. Why?

**Comment by stefanhaustein** [comment]
Unfortunately, they are wider than the character cell for the default terminal font on ubuntu.

**Comment by denizzzka** [comment]
Ok
