### ISSUE TITLE
ranger support

### ISSUE THREAD

**Issue by XaheenA** [stefanhaustein/TerminalImageViewer#21]
This is absolutely stunning work. Thanks

How can I use this in ranger as the default image previewer?

**Comment by stefanhaustein** [comment]
I am not familiar with ranger, any pointers?

**Comment by XaheenA** [comment]
[Rannger](https://github.com/ranger/ranger) a CLI filemanager: 

It's one of the best CLI applications. By default it previews images by ASCII characters. But different applications can be used, like w3m. and open an image with another application, like feh.
It would be absolutely amazing if instead of w3m and feh images could be previewed and/or viewed with TerminalImageViewer. :)

Thanks

**Comment by stefanhaustein** [comment]
I think this would need to be a feature request for ranger, as ranger will need to call tiv... I don't think there is anything I can do on the tiv side...
