### ISSUE TITLE
Using tiv for the w3m browser

### ISSUE THREAD

**Issue by HybridDog** [stefanhaustein/TerminalImageViewer#22]
Is it possible to use TerminalImageViewer to display images when using the w3m terminal webbrowser?

**Comment by stefanhaustein** [comment]
w3m seems to support changing the image viewer (see "How do I change the default image viewer?" in their [FAQ](http://w3m.sourceforge.net/FAQ). But you are probably referring to the inline image viewer? W3m probably would need to add explicit support for that. It should be relatively straightforward to use tiv as a library.
