### ISSUE TITLE
The last lines of pixels are missing

### ISSUE THREAD

**Issue by HybridDog** [stefanhaustein/TerminalImageViewer#25]
If I view the minetest mese texture upscaled by a factor of 8, the lowest pixels are missing:

mese (8x): 
![default_mese](https://user-images.githubusercontent.com/3192173/43403444-576de47c-9415-11e8-92b4-d0204b8d0ffd.png)

what tiv shows (and newlines put around it):
 ![mese_tiv](https://user-images.githubusercontent.com/3192173/43403464-669ecf4c-9415-11e8-8faa-c0d4e55917b5.png)

**Comment by HybridDog** [comment]
thanks.

**Comment by hadisfr** [comment]
I should notice that current version through away at most 3 columns from right and at most 7 rows from bottom, because it calculates color in each 4x8-pixel bucket. But for such images (128x128) and many other common size standard (4n x 8m) works correctly and shows the whole picture.

**Comment by HybridDog** [comment]
Maybe you could add a setting to display each pixel for pictures with low resolution, such as 16x16.
