### ISSUE TITLE
Decoding errors with 256 color PNG file

### ISSUE THREAD

**Issue by srett** [stefanhaustein/TerminalImageViewer#29]
I have this PNG file which either decodes with wrong colors and artifacts, or just crashes.

![lageplan_joey](https://user-images.githubusercontent.com/11955902/47911676-65d94a80-de96-11e8-994e-60c2c897c585.png)
(Here's hoping github doesn't somehow recompress images making the problem go away)

It seems this is an issue with CImg, I tried getting the latest version from their git but the problem persists. Compiling with -Dcimg_use_png and linking against libpng fixes the issue, but it seems you want to avoid linking any external libraries.

**Comment by srett** [comment]
I couldn't register with the cimg bugtracker for some reason; do you by any chance already have an account there? Otherwise I'd just try again. (I created the issue here in the meantime so it doesn't get completely lost.)

The image was created in 2015, most probably with mtpaint on Ubuntu, which at least in its current version seems to just use libpng for encoding.

**Comment by stefanhaustein** [comment]
I don't have a cimg bugtracker account. I'll close this here as there isn't much that makes sense to to here...
