### ISSUE TITLE
Don't work on Ubuntu in xfce4-terminal

### ISSUE THREAD

**Issue by jcubic** [stefanhaustein/TerminalImageViewer#3]
I've isntalled open jdk using:

```
sudo apt-get install default-jdk
```
which installed open-jdk-8 and when I've compiled java file and run the app I've got this in response:

![terminal](https://cloud.githubusercontent.com/assets/280241/16345095/5a62793a-3a40-11e6-9f1b-11e675e824b4.png)

**Comment by jcubic** [comment]
Same happen with open jdk 9

**Comment by Evizero** [comment]
what does `echo $TERM` say?

**Comment by jcubic** [comment]
xterm

**Comment by Evizero** [comment]
This looks to me like your terminal is not configured to use 256 colors (i.e. it doesn't understand the color codes that the java program writes). You could try exploring the settings of your terminal and see if you can enable 256 colors somewhere (or manually setting it in your bashrc)

**Comment by stefanhaustein** [comment]
Is this the ubuntu default terminal? Did you try the gnome terminal? Should be a terminal issue, not a jdk problem...

**Comment by jcubic** [comment]
I work for GNU head for terminals from gnu.org https://www.gnu.org/graphics/agnuheadterm.html

**Comment by stefanhaustein** [comment]
The program uses 16 million colors (24 bit rgb). Support for 256 colors will require some additional work.

**Comment by jcubic** [comment]
It work in gnome-terminal but not in xfce4-terminal

**Comment by stefanhaustein** [comment]
Hi, I haver added support for 256 colors... Can you give "java TerminalImageViewer -256 (...)" a try?

**Comment by jcubic** [comment]
Yes, it work. Great.
