### ISSUE TITLE
Create a snap

### ISSUE THREAD

**Issue by stefanhaustein** [stefanhaustein/TerminalImageViewer#32]
As suggested here: 
https://unix.stackexchange.com/questions/35333/what-is-the-fastest-way-to-view-images-from-the-terminal/377368?noredirect=1#comment887704_377368

Documentation:  https://snapcraft.io/first-snap

**Comment by stefanhaustein** [comment]
I have created a basic snap file; the current main problem is that the Makefile isn't really ideal for snap, and I am not sure about the best way to address this.

**Comment by stefanhaustein** [comment]
Update: teresaejunior has fixed the snap (thanks a lot!).
I'll look into connecting it to the repository during the next days.

**Comment by stefanhaustein** [comment]
Update: snap is available on the --edge channel, see main readme :)
Will try to setup automation next, then close this.

**Comment by raldone01** [comment]
The snap is not working for me. It always says that it doesn't recognize the file format. [CImg error] Manual install is working though.

**Comment by teresaejunior** [comment]
Here it works just fine. Maybe support for the file format you're trying to read was not compiled in the snap. What is the file format?

**Comment by raldone01** [comment]
Jpeg

**Comment by teresaejunior** [comment]
What is the complete error message?

**Comment by raldone01** [comment]
```
main@xenon:~$ whereis tiv
tiv: /usr/local/bin/tiv /snap/bin/tiv
main@xenon:~$ /snap/bin/tiv srv/data/images/animal/google-image(0540).jpeg
-bash: syntax error near unexpected token `('
main@xenon:~$ /snap/bin/tiv "/srv/data/images/animal/google-image(0540).jpeg"

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file '/srv/data/images/animal/google-image(0540).jpeg'.
File format is not recognized for '/srv/data/images/animal/google-image(0540).jpeg'
main@xenon:~$
```

**Comment by teresaejunior** [comment]
As a security precaution, Snap is not supposed to read files from /srv. It was given permission to read files from $HOME only. Not much I can do about it.

**Comment by raldone01** [comment]
Ok. That error message is very misleading. I think "Couldn't open file!" would be more clear. 
Will tiv be available via apt-get or some other non restrictive package-manager?

**Comment by teresaejunior** [comment]
>There is nothing I can do about it.

Actually, tiv can be set to use the [`classic` confinement](https://ubuntu.com/blog/how-to-snap-introducing-classic-confinement). It will need to be installed with the `--classic` option if it is decided we should go this route.

**Comment by stefanhaustein** [comment]
I think we should still improve the error message. We probably should check if the file exists before handing the path over to the decoder library...

**Comment by stefanhaustein** [comment]
Let's not handle issues not related to snap here (but continue the image issue under #75)
