### ISSUE TITLE
Cannot run using termux in android

### ISSUE THREAD

**Issue by seisdr** [stefanhaustein/TerminalImageViewer#34]
I'm using termux in android I was compiled it previously but now I get error cannot find -lstdc++fs
Any solution

**Comment by seisdr** [comment]
Probably lib missing and absolutely not exist

**Comment by seisdr** [comment]
If someone compiled it and given me the last file output that gonna work isn't?
Who will do

**Comment by seisdr** [comment]
@stefanhaustein come on man write something

**Comment by seisdr** [comment]
@loverboy0004 thanks alot
but I would like this tool been on termux

Error :(

```[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '71685113_p0_master1200.jpg'.
File format is not recognized for '71685113_p0_master1200.jpg'```

**Comment by stefanhaustein** [comment]
Maybe it's a general issue with this particular jpeg? Did you try a png?

**Comment by seisdr** [comment]
same 
```  
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'k.png'.
File format is not recognized for 'k.png'
```

**Comment by stefanhaustein** [comment]
But this doesn't look like a compilation issue, more like some libraries are missing.... did you install imagemagic as well?

**Comment by stefanhaustein** [comment]
@seisdr Can you elaborate?

**Comment by seisdr** [comment]
Your project is awesome and the print of image is better than other projects but it d

**Comment by stefanhaustein** [comment]
Thnaks! You mean animated gif (and / or video)? This would be a separate issue. 
Concerning lstdc++fs, maybe that's also related to the mac problem... Will have a look when I have updated my mac.
