### ISSUE TITLE
Redirecting tiv output

### ISSUE THREAD

**Issue by klopsi** [stefanhaustein/TerminalImageViewer#37]
Am I the only user who gets files of size 0 when i try to redirect tiv output?

Doesn't std::cout allow redirection?

**Comment by stefanhaustein** [comment]
which platform? What was the exact command? Does the same file work fine without redirection?

**Comment by stefanhaustein** [comment]
Please re-open with more information.

**Comment by rekire** [comment]
I see the same behavior. I'm using a raspberry pi (Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux)

**Comment by GottZ** [comment]
you need to specify width and height. if you specify height 99999 and width 80 it will scale down to fit into that.
it does not scale up though.

reason: it tries to read the tty width and height and sets it as default.
if it's a pipe, both default to 0 thus you have to specify it yourself.
