### ISSUE TITLE
Add in 1, 4, 8, & 16 color mode

### ISSUE THREAD

**Issue by mikeytown2** [stefanhaustein/TerminalImageViewer#39]
Nice to have in the event that the terminal doesn't support more colors.

**Comment by stefanhaustein** [comment]
I think this would require dithering to look reasonable, which doesn't really make sense to combine with the current shape matching approach... Are there actually terminals today supporting less than 256?

**Comment by GottZ** [comment]
> Are there actually terminals today supporting less than 256?

ye. old windows cmd

who cares about them though.

**Comment by stefanhaustein** [comment]
I won't object if somebody wants to add this, but I think it will look pretty awful.....

**Comment by stefanhaustein** [comment]
I am closing this as the output will look quite ugly in most cases without control over the colors and/or dithering which would require a different algorithm. I wouldn't mind if someone would add support, but I don't think it makes much sense to focus on this.

**Comment by tracker1** [comment]
I agree with @stefanhaustein and @GottZ ... The biggest issue is, in lower color modes, you won't know *WHICH* colors the terminal is actually set to.  Different terminals, and applications can and often do override the defaults.  For example, I override the defaults when in windows to match the DOS-ANSI color profile, which won't be the same as the *nix vtx profile defaults, or let alone various themes in given editors.
