### ISSUE TITLE
A way to install the app

### ISSUE THREAD

**Issue by jcubic** [stefanhaustein/TerminalImageViewer#4]
Right now the javac create bunch of class files from source file, and you need to call it from the directory where you compile it. There should be a way to install the app, for instance create jar file and bash script that will call the java with the jar file.

**Comment by stefanhaustein** [comment]
@wieczorek1990 has created a gradle script and a bunch of scripts in pull request #1: https://github.com/stefanhaustein/TerminalImageViewer/pull/1

Would that suit your needs?

**Comment by stefanhaustein** [comment]
I have ported the bulk of the code to C++ and added an install script there:
https://github.com/stefanhaustein/tiv
