### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by rekire** [stefanhaustein/TerminalImageViewer#40]
I found your tool, and checked it I can use it with putty or the windows bash. It works on both, but it is displaying that some symbols which are not supported.

How did you find out which symbols are supported so that I can try to filter them out?

![shell](https://user-images.githubusercontent.com/4619618/53699903-538ffe80-3ded-11e9-8dcd-3f6ba5d33fe0.png)

**Comment by GottZ** [comment]
just stop using old fonts and use something like inconsolata or firacode

**Comment by GottZ** [comment]
oh and you might want to use wstty

**Comment by stefanhaustein** [comment]
Alternatively, try the -0 option. I have added both options to the "Commoin problems" section on the main page.

**Comment by i-sf** [comment]
For anyone still coming to this, both Git Bash and Powershell seem to produce good results (better with the recommended fonts), I couldn't get PuTTY to work. I've written a small wrapper script that `ssh -i ~/.ssh/correct-key correct-host` and it does the trick.
