### ISSUE TITLE
To obscure when show small image

### ISSUE THREAD

**Issue by chen3feng** [stefanhaustein/TerminalImageViewer#42]
For example, a 120x120 image like this. It should use a smaller cell size for the small image.
![BearLogoRed](https://user-images.githubusercontent.com/1998410/54141744-34364880-4461-11e9-89bb-3c3614471e17.jpg)

**Comment by stefanhaustein** [comment]
Any concrete suggestion? just double the size if the image is below a certain treshold? Which one? Something else? How would this relate to other parameters (w/h)?

**Comment by stefanhaustein** [comment]
Should be addressed by #73
