### ISSUE TITLE
Which terminals does this work well with?

### ISSUE THREAD

**Issue by lgritz** [stefanhaustein/TerminalImageViewer#5]
I stumbled across this page and thought it was a really cool idea, so I tried something similar in a project I'm working on. (Not being Java-based, I can't directly use your code, but my re-implementation was certainly inspired by your ideas.)

But one thing I noticed right away is that on my Mac (where I'm using iTerm2), the rendering of the unicode block characters doesn't quite fill the character cell. So, for example, if it wants the top half to be "foreground" color and the bottom half to be the background color, you'll still see a bit of the background at the top of the cell, if you understand what I'm getting at. This really screws up the appearance versus the neat images you show on the project page.

So I'm wondering what advice you might have -- which terminal emulation programs, which platforms, which fonts are known to work or not work? And do you have any thoughts about "auto-detection" about whether the unicode characters are supported, and/or if the 24-bit color ANSI codes are supported? Must a user know that in advance and only use a display scheme like this if they somehow know, or is there a way for a program to figure out whether it's likely that the terminal being used at the moment supports it?

**Comment by stefanhaustein** [comment]
Does the gap at the top only happen for "half" blocks? If so, we may be able to fix this by using U+2584  with inverted colors instead of U+2580. Can you add a screenshot? 

Concerning terminal capabilites: I think the typical way to do this is to query some more or less reliable environment variables.

**Comment by lgritz** [comment]
Interesting, yes, switching some of the "primaries" for the commented-out inverses does improve things. But it's not perfect. In the case of U+2580 vs U-2584, it is an improvement but not a full solution. Although 2580 has at least two pixels of background at the top, 2584 still seems to have just a single background pixel at the bottom. Ick. I'm not sure if that's specific to the particular font I'm using, I've got some experimenting to do.

Which platform+terminal are you using, that it looks good?

**Comment by stefanhaustein** [comment]
Linux + Gnome Terminal. Maybe there is a way to reduce line spacing?

**Comment by stefanhaustein** [comment]
If you find a termianl for macos that works well, let me know!
