### ISSUE TITLE
Failed to recognize format

### ISSUE THREAD

**Issue by AsyDynamics** [stefanhaustein/TerminalImageViewer#56]
I build the c++ version on raspbian and ubuntu 18, both give me such error

`
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'image.jpg'.
File format is not recognized for 'image.jpg'`.

Also tried the png file but still not work. Any clue?

**Comment by histefanhere** [comment]
I'm having the same issue with both png's and jpg's, would love for this to be fixed.

**Comment by stefanhaustein** [comment]
Cimg relies on other packages (libpng, libjpeg) to handle the corresponding file formats. Can you check if you have them installed (typically cimg should depend on them). Did you check if imagemagic is installed and works properly with png and jpeg images?

**Comment by pidjey** [comment]
Had this problem on a fresh Ubuntu install. Solved this by installing imagemagick, as stefan said
