### ISSUE TITLE
having problems with screenshots

### ISSUE THREAD

**Issue by ukos-git** [stefanhaustein/TerminalImageViewer#59]
The following image gives an error:

![desktop_extracted](https://user-images.githubusercontent.com/16167358/62215332-0c5f6700-b3a7-11e9-9362-c2e76d50a2fb.png)

```
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file './desktop_extracted.jpg'.
```

Imagemagick does not have problems with it. The picture even originates from the X-window capturing tool of imagemagick.

```
> import -window root file.png
> tiv file.png

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file 'file.png'.
File format is not recognized for 'file.png'
```

**Comment by stefanhaustein** [comment]
Could this be the same problem as this one: https://github.com/stefanhaustein/TerminalImageViewer/issues/32#issuecomment-535631121

**Comment by ukos-git** [comment]
Exactly.
