### ISSUE TITLE
Brew install on macOS?

### ISSUE THREAD

**Issue by alichtman** [stefanhaustein/TerminalImageViewer#60]
It'd be cool if this were `$ brew install`-able.

**Comment by aaronliu0130** [comment]
Hey there. I'm actually working on it. I just need to provide tests(#69)...

**Comment by aaronliu0130** [comment]
@alichtman [Hey again. Currently working on it](Homebrew/homebrew-core/pull/52335)

**Comment by aaronliu0130** [comment]
[@alichtman Now that didn't go well. But I've opened a new pull request on brew!](#72 )
