### ISSUE TITLE
Possible typo with "light down"

### ISSUE THREAD

**Issue by shabbyrobe** [stefanhaustein/TerminalImageViewer#64]
Just noticed something odd in the code; it seems that even though the comment says "light down", it is using the codepoint for "light up":

https://github.com/stefanhaustein/TerminalImageViewer/blob/0721c1f9fd5f98ea9d937065697aaefc6c10297d/src/main/cpp/tiv.cpp#L90

```
  0x44440000, 0x2575,  // light up
  0x22220000, 0x2575,  // light up
  0x00030000, 0x2576,  // light right
  0x00003000, 0x2576,  // light right
  0x00004444, 0x2575,  // light down
  0x00002222, 0x2575,  // light down
```

If "light down" is actually what is wanted, the codepoint is 0x2577.

**Comment by stefanhaustein** [comment]
Yes, thanks, looks like a bug. The hex pattern looks like a vertical line from half the height to the bottom, so it should be 0x2577, as you have pointed out.

**Comment by stefanhaustein** [comment]
Fixed with https://github.com/stefanhaustein/TerminalImageViewer/commit/e79df170f55e68e0c0b90d73c70565a81aba2ea0
