### ISSUE TITLE
option to select the number of images displayed in "directory preview" mode

### ISSUE THREAD

**Issue by nkh** [stefanhaustein/TerminalImageViewer#7]
an option to force the number of images displayed side by side, default seems to be 4 but I'd like to force it to 3 or 2

**Comment by stefanhaustein** [comment]
Please use the new -c parameter (=columns) for this.

**Comment by nkh** [comment]
does not work on my box

java TerminalImageViewer -c 2 ~/nadim/downloads/*
   shows 4 columns

java TerminalImageViewer -c 2 ~/nadim/downloads
  shows one empty row
