### ISSUE TITLE
Any picture suggestions for celebrating 666 likes soon? 

### ISSUE THREAD

**Issue by stefanhaustein** [stefanhaustein/TerminalImageViewer#71]

**Comment by clort81** [comment]
![greenaliencapsm](https://user-images.githubusercontent.com/51511737/74588058-bdeb8000-4ff9-11ea-9714-e5f61c4199c3.png)
![greengcap](https://user-images.githubusercontent.com/51511737/74588066-d22f7d00-4ff9-11ea-9045-7574531ac88e.png)
![leafgirl125cap](https://user-images.githubusercontent.com/51511737/74588074-e1162f80-4ff9-11ea-965e-a4fff68b1609.png)
![marylineyescap](https://user-images.githubusercontent.com/51511737/74588078-e6737a00-4ff9-11ea-9d92-95ab3fdeba37.png)
![mengerprincap](https://user-images.githubusercontent.com/51511737/74588083-f12e0f00-4ff9-11ea-9f0a-395670cd4a10.png)
![michaelhastingscap](https://user-images.githubusercontent.com/51511737/74588089-f8551d00-4ff9-11ea-9e22-c69fc05c9f14.png)
![optimuscap](https://user-images.githubusercontent.com/51511737/74588094-07d46600-4ffa-11ea-97f3-53c9b34e3fe2.png)
![peanutsdancecap](https://user-images.githubusercontent.com/51511737/74588099-102ca100-4ffa-11ea-9950-a7e9d11508a5.png)
![pineconecap](https://user-images.githubusercontent.com/51511737/74588102-1753af00-4ffa-11ea-81b7-174ffc14eab1.png)
![popartcap](https://user-images.githubusercontent.com/51511737/74588127-32262380-4ffa-11ea-81f2-d8b64ca1e391.png)
![wariocap](https://user-images.githubusercontent.com/51511737/74588136-4e29c500-4ffa-11ea-81e7-7ef5462964bc.png)
![got2cap](https://user-images.githubusercontent.com/51511737/74588159-6d285700-4ffa-11ea-84ac-09b48f9471af.png)
![nofreedomcap](https://user-images.githubusercontent.com/51511737/74588181-803b2700-4ffa-11ea-8ceb-73c2a5d6b8bb.png)

**Comment by stefanhaustein** [comment]
Thanks for the suggestions! Forgot to close the issue -- had used this one to celebrate: https://twitter.com/dukoid/status/1223355300889141249
