### ISSUE TITLE
TIV fails to load single valid png

### ISSUE THREAD

**Issue by MarkJeronimus** [stefanhaustein/TerminalImageViewer#75]
Accidentally created issue then realized this was already discussed in #32

**Comment by stefanhaustein** [comment]
I have downloaded the image and it seems to work for me...
![bad_image_working](https://user-images.githubusercontent.com/4282319/80860154-3ca1a200-8c66-11ea-9266-8d91e6eec95e.png)

Is this just reproducible with the snap for you -- or also at head? Any idea which version of ImageMagic you are linking

**Comment by stefanhaustein** [comment]
p.s. Might be an issue with the path being outside of the access permissions for the snap? I think I still haven't fixed the error message for that problem....

**Comment by stefanhaustein** [comment]
Should be fixed by 37dc1f9b071e2452ea0e6ee90f570f17d1e0b218 -- but I still need to update the snap....
