### ISSUE TITLE
homebrew file need update, 

### ISSUE THREAD

**Issue by cxwx** [stefanhaustein/TerminalImageViewer#76]
mac homebrew mv gcc to /usr/local/opt/gcc
not in /usr/local

new libstdc++fs at  /usr/local/opt/gcc/lib

```
ld: library not found for -lstdc++fs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by neosun100** [comment]
same error，how to solve？

**Comment by neosun100** [comment]
```rb
$ brew install terminalimageviewer.rb 
==> Downloading https://github.com/stefanhaustein/TerminalImageViewer/archive/v1.0.0.tar.gz
==> Downloading from https://codeload.github.com/stefanhaustein/TerminalImageViewer/tar.gz/v1.0.0
######################################################################## 100.0%
==> make
Last 15 lines from /Users/neo/Library/Logs/Homebrew/terminalimageviewer/01.make:
2020-05-07 19:08:33 +0800

make

g++ -std=c++17  -Wall -fpermissive -fexceptions -O2 -c tiv.cpp -o tiv.o
g++ tiv.o -o tiv -lstdc++fs -pthread -s
ld: library not found for -lstdc++fs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tiv] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by cxwx** [comment]
you should add
```
override LDLIBS   += -L/usr/local/opt/gcc/lib/gcc/9/ -lstdc++fs
```
@ makefile, 
or set it in your personal environment

**Comment by neosun100** [comment]
cool！thanks!

**Comment by stefanhaustein** [comment]
+aaronliu0130

**Comment by stefanhaustein** [comment]
@aaronliu0130

**Comment by aaronliu0130** [comment]
Welcome to macOS, the cradle of innovation! I think this can be resolved by adding that -L  into the homebrew file. I'll check for a moment.

**Comment by aaronliu0130** [comment]
Well there's something wrong with my mac, so let me try to make github actions do it.

**Comment by aaronliu0130** [comment]
Yes, the CI failed, so status-confirmed. Let's try taking the -L...

**Comment by stefanhaustein** [comment]
Any update? I think if we want to keep homebrew support we need a volunteer for maintenance? Does this make sense?

**Comment by cxwx** [comment]
I wrote an example https://github.com/cxwx/homebrew-cxbrew/blob/master/Formula/terminalimageviewer.rb
```
brew tap cxwx/cxbrew
brew install terminalimageviewer
```

**Comment by aaronliu0130** [comment]
> Any update? I think if we want to keep homebrew support we need a volunteer for maintenance? Does this make sense?

Sorry for the wait. I don't have much time now especially as school as started. Yes, I think we do need a volunteer.

> I wrote an example https://github.com/cxwx/homebrew-cxbrew/blob/master/Formula/terminalimageviewer.rb
> 
> ```
> brew tap cxwx/cxbrew
> brew install terminalimageviewer
> ```

@cxwx Gee thanks! It would be a lot better if you cloned this repository and merged your commits. That way you will take full credit for it.

**Comment by stefanhaustein** [comment]
I think it doesn't make sense to have non-working homebrew support, but I can't manage it. 

So either somebody steps up to support homebrew, or it would be cleaner to remove it -- compared to pretending it works....

**Comment by cxwx** [comment]
I've upgrade my homebrew to lastest V1.1.0, but not standard format of homebrew
just use
```
brew install cxwx/cxbrew/terminalimageviewer
```

**Comment by aaronliu0130** [comment]
> I think it doesn't make sense to have non-working homebrew support, but I can't manage it.
> 
> So either somebody steps up to support homebrew, or it would be cleaner to remove it -- compared to pretending it works....

I'll go ahead merge these changes and make a pull request giving credit then.

**Comment by cxwx** [comment]
good job @aaronliu0130
