### ISSUE TITLE
[install] arm64

### ISSUE THREAD

**Issue by DLsnowman** [stefanhaustein/TerminalImageViewer#78]
hello, how to install on arm64

**Comment by aaronliu0130** [comment]
@DLsnowman What is your operating system? If it is linux/unix, just follow the instructions in the README.

**Comment by clort81** [comment]
aarch64 compiles fine here

**Comment by DLsnowman** [comment]
@aaronliu0130 @clort81 I'm using a jetson nano , ubuntu18.04.4 minized version. I close the graph service and only run by command line mode. when I input:
     sudo snap install --edge tiv
an error happens: 
    error: snap "tiv" is not available on edge for this architecture (arm64) but
       exists on other architectures (amd64).
I input the command today again. And receive the same error.

**Comment by stefanhaustein** [comment]
Closing as this seems to be not reproducible
