### ISSUE TITLE
Feature Request: Add macOS g++(clang++) support

### ISSUE THREAD

**Issue by aaronliu0130** [stefanhaustein/TerminalImageViewer#83]
One major reason TIV wasn't accepted to homebrew-core was because it didn't have support for clang++. I suggest we find a way to use alternatives to the filesystem library. One option would be to use the filesystem library from boost, which homebrew allows. We need to do this, especially as installing homebrew packages directly from a URL is now deprecated.

**Comment by stefanhaustein** [comment]
Isn't the standard fs library based on boost anyway? Does boost "just work" with GCC without further installation? How far out is proper fs support for clang?

**Comment by aaronliu0130** [comment]
> Isn't the standard fs library based on boost anyway? Does boost "just work" with GCC without further installation? How far out is proper fs support for clang?

As we know clang doesn't have filesystem support just yet. So all we have to do is to find an easy alternative. After installing boost I'm sure it "just works", though it takes up some unnecessary space on Linux.  Maybe we can make a separate program in the same folder almost the same as the original but with boost support? Then we'd change the homebrew file to compile the macOS file on macOS and it would probably be accepted to homebrew-core. I'm not that good in programming though, so I can't port it by myself.

**Comment by stefanhaustein** [comment]
I'll migrate the fs stuff to boost when I get a chance

**Comment by aaronliu0130** [comment]
https://www.boost.org/doc/libs/1_34_1/libs/filesystem/doc/index.htm
The syntax is the same.

**Comment by stefanhaustein** [comment]
Does this problem still exist?

**Comment by aaronliu0130** [comment]
No.
