### ISSUE TITLE
images smaller than terminal

### ISSUE THREAD

**Issue by nkh** [stefanhaustein/TerminalImageViewer#9]
in 120+ terminal, the image is just 86 wide

option -w 120, changes nothing
option -w 200, changes nothing

option -W 200 makes the image very small!

**Comment by stefanhaustein** [comment]
-h defaults to 25 --- Set -h, too?

**Comment by nkh** [comment]
it doesn't matter what -h is set to. 

another example is if I say -w 10 - h 50, it will be wider than 1o, actually it is always the same size except when it is small, then it is always the same small size.

I run the latest from git

**Comment by stefanhaustein** [comment]
Can you supply the image so I can check? Maybe it's quite small -- IIRC, there is no upscaling, just downscaling....

**Comment by nkh** [comment]
any image but here is one

![linux-software](https://cloud.githubusercontent.com/assets/45409/19264872/fd7204a8-8fa2-11e6-8789-c1fd1b5085ac.jpg)

**Comment by stefanhaustein** [comment]
I think in this case the issue is that there is no upscaling, just downscaling. Not sure yet what the best solution is. Probably will change the default to scale both ways to fit into the supplied dimensions.

**Comment by stefanhaustein** [comment]
Ok, the code looks like it should scale to fit the height and width without distortion. 
Try -w 200 -h 1000
