### ISSUE TITLE
File format is not recognized for 'test.jpg'

### ISSUE THREAD

**Issue by breaklien** [stefanhaustein/TerminalImageViewer#96]
Tested on Ubuntu 18.04:
```bash
$ tiv test.jpg -0

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file 'test.jpg'.
File format is not recognized for 'test.jpg'
```

Test Image:
https://pbs.twimg.com/media/EtXBnqTU0AAhyAC?format=jpg&name=large

**Comment by aaronliu0130** [comment]
> Tested on Ubuntu 18.04:
> 
> ```shell
> $ tiv test.jpg -0
> 
> [CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file 'test.jpg'.
> File format is not recognized for 'test.jpg'
> ```
> 
> Test Image:
> https://pbs.twimg.com/media/EtXBnqTU0AAhyAC?format=jpg&name=large

@breaklien 
That's a jfif image you've got there, not a jpg, which confuses cimg to use the wrong thing to read the file. Try renaming it to test.jfif and try again.

PS: PLEASE USE A SFW IMAGE NEXT TIME, OR AT LEAST PUT A WARNING! sorry for lashing out

**Comment by aaronliu0130** [comment]
> Tested on Ubuntu 18.04:
> 
> ```shell
> $ tiv test.jpg -0
> 
> [CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to open file 'test.jpg'.
> File format is not recognized for 'test.jpg'
> ```
> 
> Test Image:
> https://pbs.twimg.com/media/EtXBnqTU0AAhyAC?format=jpg&name=large

@breaklien 
That's a jfif image you've got there, not a jpg, which confuses cimg to use the wrong thing to read the file. Try renaming it to test.jfif and try again.

PS: PLEASE USE A SFW IMAGE NEXT TIME, OR AT LEAST PUT A WARNING! sorry for lashing out

**Comment by aaronliu0130** [comment]
@breaklien follow up plz

**Comment by stefanhaustein** [comment]
The test image seems to be gone, so we can't repro, and aaron's investigation seems to indicate that the file extension didn't match the format
