### ISSUE TITLE
Does not play well with mosh

### ISSUE THREAD

**Issue by karelbilek** [stefanhaustein/TerminalImageViewer#97]
I am trying to use tiv together with mosh - a "mobile shell", that is doing some magic to work properly in low latency environments

https://mosh.org

(basically they have a completely different protocol than SSH, that synchronizes the screens)

Now I guess it is not playing nice with unicode magic that you do here. When I try `tiv` with `mosh`, all pictures looks garbled and ugly.

**Comment by karelbilek** [comment]
Ah it seems like mosh is unmaintained, based on the comments here

https://github.com/mobile-shell/mosh/issues/1115

**Comment by aaronliu0130** [comment]
Could you provide some screenshots? Thanks.

**Comment by karelbilek** [comment]
<img width="492" alt="Screen Shot 2021-04-12 at 13 32 50" src="https://user-images.githubusercontent.com/104945/114350629-a2dfb600-9b93-11eb-93d2-b680a9b35094.png">

This is "Lenna".

**Comment by karelbilek** [comment]
This is on the same machine, both server and client, just through normal ssh.

<img width="487" alt="Screen Shot 2021-04-12 at 13 34 34" src="https://user-images.githubusercontent.com/104945/114350769-db7f8f80-9b93-11eb-805b-ba95c1d3c19d.png">

**Comment by karelbilek** [comment]
Note, I think it might be something on mosh side, it is not maintained anymore and it does some complex magic.

**Comment by PythonNut** [comment]
I imagine this is because mosh doesn't support 24bit colors (at least not using version <= `1.3.2`).

**Comment by karelbilek** [comment]
Ah.

I used whatever version was in homebrew. ...yes, 1.3.2.

Oh, that is the latest release.

**Comment by stefanhaustein** [comment]
Did you try the 256 or 16 color options? Perhaps mosh doesn't support 24
bit color?

Am Mo., 12. Apr. 2021 um 08:40 Uhr schrieb Karel Bilek <
***@***.***>:

**Comment by karelbilek** [comment]
Ahhh 256 works. That's it, thanks!

**Comment by karelbilek** [comment]
Closing this, as it is "solved". (good enough.)
