### ISSUE TITLE
Doesn't work on macOS unless 256 color mode is selected

### ISSUE THREAD

**Issue by aaronliu0130** [stefanhaustein/TerminalImageViewer#99]
![image](https://user-images.githubusercontent.com/11874211/119212857-b0228580-baed-11eb-8da9-22a8c9954cd0.png)
![image](https://user-images.githubusercontent.com/11874211/119212896-f7a91180-baed-11eb-9056-ff804db3c970.png)
![image](https://user-images.githubusercontent.com/11874211/119212889-eb24b900-baed-11eb-9807-c376051a3b63.png)
![image](https://user-images.githubusercontent.com/11874211/119212906-042d6a00-baee-11eb-9b4b-31bf3750df58.png)
Image:
![Cornell Box](https://upload.wikimedia.org/wikipedia/commons/2/24/Cornell_box.png)

**Comment by stefanhaustein** [comment]
This is true but it's also documented in README.md

I don't think there is a way for us to fix this, as this seems to be a limitation of the MacOS shell.

**Comment by stefanhaustein** [comment]
So I'd say it's working as expected...
